import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import Link from "next/link";
import { cn } from "@/lib/utils";
import { ClerkProvider, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";
import { Button } from "@/components/ui/button";
import Image from "next/image";
import { Cover } from "@/components/ui/cover";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Cards AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable
          )}
        >
          <Cover>
          <nav className="w-screen  flex h-15 p-5 justify-between items-center">
        <div className="bold text-xl">
          <Link href={'/'}> 
          {/* <Cover className="text-white bold text-4xl bolder"> */}
            <Image src={'/cards.png'} alt="logo" width={100} height={100} />
          {/* </Cover> */}
          </Link>
        </div>
        <div>
          <SignedOut>
            <div className="flex gap-5">
              <Link href={'/sign-in'}><Button>Login</Button></Link>
              <Link href={'/sign-up'}><Button>Signup</Button></Link>
            </div>
            
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn>
        </div>
     </nav>
     </Cover>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
